import type { APIRoute } from 'astro';

/**
 * Service worker: make the last committed dataset readable offline.
 *
 * The whole site is static HTML built from a dataset that changes every six
 * hours, which makes it unusually well suited to this — there is no session, no
 * personalisation baked into a page, and yesterday's figures are still true as
 * of yesterday. What it must never do is make the site look live when it is
 * not, so:
 *
 * - **Navigations are network-first.** A fresh page wins whenever the network
 *   answers; the cache is the fallback, not the default. A stale-while-
 *   revalidate strategy would show a reader a figure from four refreshes ago
 *   with no way to tell.
 * - **Hashed build assets are cache-first**, because their URL changes when
 *   their content does. That is what the hash is for.
 * - **The two sanctioned external fetches are never touched.** CoinGecko and
 *   mempool.space are live-by-definition; serving either from a cache would
 *   turn "live" into a lie. They are cross-origin, so the fetch handler
 *   ignores them outright rather than relying on a URL match.
 *
 * Generated as a route so `BASE_URL` is compiled in — a worker registered from
 * a subpath can only control that subpath, and a hardcoded '/' scope silently
 * controls nothing here.
 */
export const GET: APIRoute = () => {
  const base = import.meta.env.BASE_URL.replace(/\/$/, '');
  const body = `/* Generated by src/pages/sw.js.ts — do not edit in dist. */
const VERSION = 'blockplot-v1';
const BASE = ${JSON.stringify(base)};
const OFFLINE_FALLBACK = BASE + '/';

self.addEventListener('install', (event) => {
  // Only the shell. Every other page is cached as it is visited, so a reader
  // who never opens /network/ does not carry it around.
  event.waitUntil(
    caches.open(VERSION).then((cache) => cache.addAll([OFFLINE_FALLBACK])).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  // Drop caches from older versions, then take over open tabs.
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Cross-origin is left entirely alone: that is the live price and the live
  // fee tiers, and a cached "live" figure is worse than no figure.
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(BASE + '/')) return;

  // Hashed assets: the URL changes when the bytes do, so the cache cannot go
  // stale and the network round-trip is pure cost.
  if (url.pathname.includes('/_astro/')) {
    event.respondWith(
      caches.match(request).then(
        (hit) =>
          hit ||
          fetch(request).then((response) => {
            const copy = response.clone();
            caches.open(VERSION).then((cache) => cache.put(request, copy));
            return response;
          }),
      ),
    );
    return;
  }

  // Everything else — pages, the manifest, the feeds — is network-first, so a
  // reader online always sees the newest committed figures.
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(VERSION).then((cache) => cache.put(request, copy));
        }
        return response;
      })
      .catch(() =>
        caches
          .match(request)
          .then((hit) => hit || (request.mode === 'navigate' ? caches.match(OFFLINE_FALLBACK) : undefined))
          .then((hit) => hit || Response.error()),
      ),
  );
});
`;
  return new Response(body, { headers: { 'content-type': 'text/javascript; charset=utf-8' } });
};
